export const diseaseDynamicsProfiles = {
  normal: {
    label: "Normal",
    classicalMultiplier: 1,
    lectinMultiplier: 1,
    alternativeMultiplier: 1,
    terminalMultiplier: 1,
    regulationMultiplier: 1,
    c3bBbPersistence: 1,
    macMultiplier: 1,
    c5aMultiplier: 1,
    cd55Default: null,
    cd59Default: null
  },
  PNH: {
    label: "PNH",
    classicalMultiplier: 1,
    lectinMultiplier: 1,
    alternativeMultiplier: 1.08,
    terminalMultiplier: 1.35,
    regulationMultiplier: 0.82,
    c3bBbPersistence: 1.08,
    macMultiplier: 2.25,
    c5aMultiplier: 1.1,
    cd55Default: 25,
    cd59Default: 18
  },
  aHUS: {
    label: "aHUS",
    classicalMultiplier: 1.05,
    lectinMultiplier: 1,
    alternativeMultiplier: 1.45,
    terminalMultiplier: 1.18,
    regulationMultiplier: 0.48,
    c3bBbPersistence: 1.35,
    macMultiplier: 1.38,
    c5aMultiplier: 1.18,
    cd55Default: null,
    cd59Default: null
  },
  C3G: {
    label: "C3G",
    classicalMultiplier: 0.95,
    lectinMultiplier: 0.95,
    alternativeMultiplier: 1.72,
    terminalMultiplier: 1.05,
    regulationMultiplier: 0.62,
    c3bBbPersistence: 1.85,
    macMultiplier: 1.15,
    c5aMultiplier: 1.08,
    cd55Default: null,
    cd59Default: null
  },
  AMD: {
    label: "Age-related Macular Degeneration",
    diseaseName: "Age-related Macular Degeneration",
    primaryTissue: ["retina", "macula", "RPE", "choroid"],
    primaryPathway: "alternative complement pathway",
    secondarySystems: ["immune", "vascular", "brain association", "kidney association"],
    keyBiomarkers: ["C3", "C3a", "C3b", "C5a", "sC5b-9", "Factor H", "Factor I", "Factor B", "Bb"],
    geneticAssociations: ["CFH", "C3", "CFB", "CFI", "ARMS2/HTRA1"],
    diseaseModifiers: {
      alternativePathwayActivityMultiplier: 1.3,
      factorHRegulationMultiplier: 0.75,
      chronicInflammationMultiplier: 1.25,
      retinalTissueSensitivityMultiplier: 1.5,
      macFormationLocalRiskMultiplier: 1.2
    },
    classicalMultiplier: 0.95,
    lectinMultiplier: 1,
    alternativeMultiplier: 1.34,
    terminalMultiplier: 1.05,
    regulationMultiplier: 0.82,
    c3bBbPersistence: 1.18,
    macMultiplier: 1.1,
    c5aMultiplier: 1.12,
    cd55Default: null,
    cd59Default: null
  },
  sepsis: {
    label: "Sepsis",
    classicalMultiplier: 1.32,
    lectinMultiplier: 1.25,
    alternativeMultiplier: 1.26,
    terminalMultiplier: 1.45,
    regulationMultiplier: 0.88,
    c3bBbPersistence: 1.15,
    macMultiplier: 1.25,
    c5aMultiplier: 2,
    cd55Default: null,
    cd59Default: null
  },
  "cancer microenvironment": {
    label: "Cancer microenvironment",
    classicalMultiplier: 1.08,
    lectinMultiplier: 1.06,
    alternativeMultiplier: 1.18,
    terminalMultiplier: 1.12,
    regulationMultiplier: 0.92,
    c3bBbPersistence: 1.12,
    macMultiplier: 1.05,
    c5aMultiplier: 1.62,
    cd55Default: null,
    cd59Default: null
  }
};
