export const entities = [
  entity("C1q", "C1q", "protein", "Classical pathway recognition molecule binding immune complexes.", ["classical"], [], ["C1r", "C1s"], ["C1 inhibitor"], ["lupus nephritis"], ["C1s inhibitors"], "reported"),
  entity("C1r", "C1r", "protein", "Serine protease component of the C1 complex.", ["classical"], ["C1q"], ["C1s"], ["C1 inhibitor"], ["lupus nephritis"], ["C1s inhibitors"], "reported"),
  entity("C1s", "C1s", "protein", "Classical pathway protease that cleaves C4 and C2.", ["classical"], ["C1q", "C1r"], ["C4", "C2"], ["C1 inhibitor"], ["lupus nephritis"], ["C1s inhibitors"], "reported"),
  entity("C2", "C2", "protein", "Component cleaved to form classical and lectin pathway C3 convertase.", ["classical", "lectin"], ["C1s", "MASP-2"], ["C4b2a"], [], [], [], "reported"),
  entity("C4", "C4", "protein", "Classical and lectin pathway substrate forming C4b-containing convertases.", ["classical", "lectin"], ["C1s", "MASP-2"], ["C4b2a"], ["C1 inhibitor"], ["lupus nephritis"], [], "reported"),
  entity("C4b2a", "C4b2a", "enzyme_complex", "Classical and lectin pathway C3 convertase.", ["classical", "lectin"], ["C4", "C2"], ["C3"], ["DAF / CD55"], ["lupus nephritis"], ["C1s inhibitors", "MASP-2 inhibitors"], "reported"),
  entity("C1 inhibitor", "SERPING1", "regulator", "Regulator of C1r/C1s and lectin pathway proteases.", ["classical", "lectin", "regulatory"], ["C1r", "C1s"], ["C4"], [], [], [], "reported"),

  entity("MBL", "MBL", "protein", "Lectin pathway pattern-recognition molecule.", ["lectin"], [], ["MASP-1", "MASP-2"], [], ["sepsis"], ["MASP-2 inhibitors"], "reported"),
  entity("Ficolin", "FCN", "protein", "Lectin pathway recognition family interacting with MASP proteases.", ["lectin"], [], ["MASP-1", "MASP-2"], [], ["sepsis"], ["MASP-2 inhibitors"], "reported"),
  entity("MASP-1", "MASP1", "protein", "Lectin pathway protease supporting activation and MASP-2 function.", ["lectin"], ["MBL", "Ficolin"], ["C2"], ["C1 inhibitor"], [], ["MASP-2 inhibitors"], "reported"),
  entity("MASP-2", "MASP2", "protein", "Lectin pathway protease cleaving C4 and C2.", ["lectin"], ["MBL", "Ficolin"], ["C4", "C2"], ["C1 inhibitor"], ["IgA nephropathy"], ["MASP-2 inhibitors"], "reported"),
  entity("MASP-3", "MASP3", "protein", "Lectin pathway-associated protease with links to alternative pathway maturation.", ["lectin", "alternative"], ["MBL"], ["Factor D"], [], [], [], "hypothesis"),

  entity("C3", "C3", "protein", "Central complement component cleaved into C3a and C3b.", ["classical", "lectin", "alternative"], ["C4b2a", "C3bBb"], ["C3a", "C3b"], ["Factor H", "Factor I"], ["C3 glomerulopathy", "AMD", "geographic atrophy"], ["C3 inhibitors"], "reported"),
  entity("C3(H2O)", "C3(H2O)", "fragment", "Hydrolyzed C3 generated by tick-over and alternative pathway initiation.", ["alternative"], ["C3"], ["Factor B"], ["Factor H"], ["C3 glomerulopathy"], ["Factor B inhibitors", "Factor D inhibitors"], "reported"),
  entity("C3a", "C3a", "fragment", "Anaphylatoxin generated during C3 cleavage.", ["inflammatory"], ["C3"], ["C3aR"], [], ["sepsis", "neuroinflammation"], [], "reported"),
  entity("C3b", "C3b", "fragment", "Opsonin and alternative pathway amplification platform.", ["alternative"], ["C3"], ["C3bBb", "C5"], ["Factor H", "Factor I", "MCP / CD46", "CR1"], ["C3 glomerulopathy", "aHUS"], ["C3 inhibitors", "Factor B inhibitors"], "reported"),
  entity("Factor B", "CFB", "protein", "Alternative pathway zymogen that binds C3b and is cleaved by Factor D.", ["alternative"], ["C3b"], ["Factor Bb", "C3bBb"], [], ["C3 glomerulopathy", "AMD"], ["Factor B inhibitors"], "reported"),
  entity("Factor Bb", "Bb", "fragment", "Protease fragment of Factor B within alternative C3 convertase.", ["alternative"], ["Factor B"], ["C3bBb"], ["Factor H"], ["C3 glomerulopathy"], ["Factor B inhibitors"], "reported"),
  entity("Factor D", "CFD", "protein", "Alternative pathway protease that cleaves C3b-bound Factor B.", ["alternative"], ["MASP-3"], ["Factor Bb"], [], ["AMD"], ["Factor D inhibitors"], "reported"),
  entity("Properdin", "CFP", "regulator", "Positive regulator stabilizing alternative pathway convertases.", ["alternative", "regulatory"], ["C3bBb"], ["C3 activation"], ["Factor H"], ["C3 glomerulopathy"], [], "reported"),
  entity("C3bBb", "C3bBb", "enzyme_complex", "Alternative pathway C3 convertase and amplification engine.", ["alternative"], ["C3b", "Factor B", "Factor D"], ["C3", "C5"], ["Factor H", "Factor I", "DAF / CD55"], ["C3 glomerulopathy", "aHUS", "AMD"], ["Factor B inhibitors", "Factor D inhibitors"], "reported"),
  entity("Factor H", "CFH", "regulator", "Major soluble alternative pathway regulator and cofactor for Factor I.", ["alternative", "regulatory"], ["C3b"], ["iC3b"], [], ["aHUS", "AMD", "C3 glomerulopathy"], ["complement regulators"], "reported"),
  entity("Factor I", "CFI", "regulator", "Protease that cleaves C3b/C4b with cofactors.", ["regulatory"], ["C3b", "C4b"], ["iC3b"], ["Factor H", "MCP / CD46", "CR1"], ["aHUS", "C3 glomerulopathy"], ["complement regulators"], "reported"),
  entity("DAF / CD55", "CD55", "regulator", "Membrane regulator accelerating convertase decay.", ["regulatory"], ["C3bBb", "C4b2a"], ["convertase decay"], [], ["PNH"], ["complement regulators"], "reported"),
  entity("MCP / CD46", "CD46", "regulator", "Membrane cofactor for Factor I-mediated cleavage of C3b/C4b.", ["regulatory"], ["C3b", "C4b"], ["iC3b"], [], ["aHUS"], ["complement regulators"], "reported"),
  entity("CR1", "CR1", "receptor", "Receptor and regulator promoting immune adherence and C3b/C4b processing.", ["regulatory", "receptor"], ["C3b", "C4b"], ["immune clearance"], [], ["lupus nephritis"], [], "reported"),

  entity("C5", "C5", "protein", "Terminal pathway substrate cleaved into C5a and C5b.", ["terminal"], ["C3bBb", "C4b2a"], ["C5a", "C5b"], [], ["PNH", "myasthenia gravis", "neuromyelitis optica"], ["C5 inhibitors"], "reported"),
  entity("C5a", "C5a", "fragment", "Potent inflammatory anaphylatoxin acting through C5a receptors.", ["terminal", "inflammatory"], ["C5"], ["C5aR1", "C5aR2"], [], ["sepsis", "cancer microenvironment", "neuroinflammation"], ["C5a inhibitors", "C5aR inhibitors"], "reported"),
  entity("C5b", "C5b", "fragment", "Terminal pathway fragment initiating MAC assembly.", ["terminal"], ["C5"], ["C6", "C7", "C8", "C9", "MAC"], ["CD59"], ["PNH"], ["C5 inhibitors"], "reported"),
  entity("C6", "C6", "protein", "Terminal pathway MAC component.", ["terminal"], ["C5b"], ["MAC"], ["CD59"], ["PNH"], ["C5 inhibitors"], "reported"),
  entity("C7", "C7", "protein", "Terminal pathway MAC component.", ["terminal"], ["C5b"], ["MAC"], ["CD59"], ["PNH"], ["C5 inhibitors"], "reported"),
  entity("C8", "C8", "protein", "Terminal pathway MAC component.", ["terminal"], ["C5b"], ["MAC"], ["CD59"], ["PNH"], ["C5 inhibitors"], "reported"),
  entity("C9", "C9", "protein", "Terminal pathway polymerizing MAC component.", ["terminal"], ["C5b"], ["MAC"], ["CD59"], ["PNH"], ["C5 inhibitors"], "reported"),
  entity("MAC", "C5b-9", "enzyme_complex", "Membrane attack complex and terminal complement effector.", ["terminal"], ["C5b", "C6", "C7", "C8", "C9"], ["cell lysis"], ["CD59"], ["PNH", "aHUS"], ["C5 inhibitors"], "reported"),
  entity("CD59", "CD59", "regulator", "Membrane regulator preventing terminal MAC assembly.", ["terminal", "regulatory"], ["C5b-9"], ["MAC inhibition"], [], ["PNH"], ["complement regulators"], "reported"),

  entity("C3aR", "C3AR1", "receptor", "Receptor for C3a inflammatory signaling.", ["receptor", "inflammatory"], ["C3a"], ["inflammation"], [], ["sepsis"], [], "reported"),
  entity("C5aR1", "C5AR1", "receptor", "Major receptor for C5a inflammatory signaling.", ["receptor", "inflammatory"], ["C5a"], ["neutrophil activation"], [], ["sepsis", "cancer microenvironment"], ["C5aR inhibitors"], "reported"),
  entity("C5aR2", "C5AR2", "receptor", "C5a receptor with context-dependent signaling roles.", ["receptor", "inflammatory"], ["C5a"], ["immune modulation"], [], ["cancer microenvironment"], ["C5aR inhibitors"], "reported"),
  entity("CR2", "CR2", "receptor", "Complement receptor for C3d and B-cell costimulation.", ["receptor"], ["C3 fragments"], ["B cell signaling"], [], ["lupus nephritis"], [], "reported"),
  entity("CR3", "CR3", "receptor", "Integrin receptor binding iC3b and supporting phagocytosis.", ["receptor"], ["iC3b"], ["phagocytosis"], [], ["infection"], [], "reported"),
  entity("CR4", "CR4", "receptor", "Integrin complement receptor participating in immune-cell adhesion and phagocytosis.", ["receptor"], ["iC3b"], ["phagocytosis"], [], ["infection"], [], "reported"),

  biomarker("CH50", "Classical pathway hemolytic activity screen."),
  biomarker("AH50", "Alternative pathway hemolytic activity screen."),
  biomarker("C3 level", "Clinical concentration marker for complement consumption or deficiency."),
  biomarker("C4 level", "Clinical marker often linked to classical/lectin activation."),
  biomarker("sC5b-9", "Soluble terminal complement complex marker."),
  biomarker("Bb", "Alternative pathway activation marker."),
  biomarker("Ba", "Factor B activation fragment."),

  disease("PNH", "CD55/CD59 deficiency causing uncontrolled complement-mediated RBC lysis.", ["terminal"], ["LDH", "hemolysis", "sC5b-9"], ["C5", "C3", "Factor D", "Factor B"]),
  disease("aHUS", "Alternative pathway dysregulation with endothelial injury risk.", ["alternative", "terminal"], ["C3", "Bb", "sC5b-9"], ["C5", "Factor H", "Factor I"]),
  disease("C3 glomerulopathy", "Alternative pathway dysregulation and C3 convertase stabilization.", ["alternative"], ["low C3", "Bb", "C3 fragments"], ["C3", "Factor B", "Factor D"]),
  disease("IgA nephropathy", "Mucosal immune and lectin/alternative pathway involvement in kidney injury.", ["lectin", "alternative"], ["C3", "C4d", "MASP-2"], ["MASP-2", "Factor B"]),
  disease("lupus nephritis", "Immune complex-driven classical pathway activation in kidney inflammation.", ["classical"], ["C3", "C4", "CH50"], ["C1s", "C5"]),
  disease("AMD", "Chronic alternative pathway activation and local inflammation.", ["alternative"], ["C3 fragments", "Factor H", "Bb"], ["C3", "Factor D", "Factor B", "C5"]),
  disease("geographic atrophy", "Advanced AMD context with complement-targeted therapeutic relevance.", ["alternative"], ["C3 fragments", "C5"], ["C3", "C5"]),
  disease("neuromyelitis optica", "Antibody-mediated complement activation in CNS inflammatory disease.", ["classical", "terminal"], ["C5", "sC5b-9"], ["C5"]),
  disease("myasthenia gravis", "Autoantibody-driven complement injury at neuromuscular junction.", ["classical", "terminal"], ["C5", "sC5b-9"], ["C5"]),
  disease("sepsis", "High inflammatory complement activation, especially C5a-driven signaling.", ["inflammatory", "terminal"], ["C5a", "C3a", "sC5b-9"], ["C5a", "C5aR1"]),
  disease("cancer microenvironment", "Context-dependent complement effects on inflammation, immune suppression, and angiogenesis.", ["inflammatory"], ["C5a", "C3a"], ["C5aR1", "C3"]),
  disease("neuroinflammation", "Complement-mediated synaptic, glial, and inflammatory processes.", ["inflammatory"], ["C3a", "C5a"], ["C3", "C5aR1"]),

  drug("C1s inhibitors", "C1s", "antibody", "Reduce classical pathway activation upstream of C4/C2 convertase formation."),
  drug("MASP-2 inhibitors", "MASP-2", "antibody", "Reduce lectin pathway activation upstream of C4/C2 convertase formation."),
  drug("C3 inhibitors", "C3", "peptide", "Broad upstream suppression of C3a, C3b, C5a, and MAC generation."),
  drug("Factor B inhibitors", "Factor B", "small_molecule", "Reduce alternative pathway amplification while partly preserving classical/lectin initiation."),
  drug("Factor D inhibitors", "Factor D", "small_molecule", "Reduce alternative pathway amplification by limiting Factor B cleavage."),
  drug("C5 inhibitors", "C5", "antibody", "Reduce C5a and MAC while leaving upstream C3 activation and C3b deposition intact."),
  drug("C5a inhibitors", "C5a", "antibody", "Reduce C5a inflammatory signaling without directly blocking MAC formation."),
  drug("C5aR inhibitors", "C5aR1", "small_molecule", "Reduce C5a receptor signaling and inflammatory amplification."),
  drug("complement regulators", "Factor H / CD55 / CD59", "fusion_protein", "Restore or mimic endogenous regulation in context-specific ways.")
];

export const relationships = [
  rel("C1q", "C1r", "activates", "Immune-complex recognition activates the C1 complex.", "reported"),
  rel("C1r", "C1s", "activates", "C1r activates C1s within the C1 complex.", "reported"),
  rel("C1s", "C4", "cleaves", "C1s cleaves C4 during classical pathway activation.", "reported"),
  rel("C1s", "C2", "cleaves", "C1s cleaves C2 to form the C4b2a convertase.", "reported"),
  rel("C4", "C4b2a", "forms_complex_with", "C4b and C2a form the classical/lectin C3 convertase.", "reported"),
  rel("C2", "C4b2a", "forms_complex_with", "C2a participates in C4b2a formation.", "reported"),
  rel("MBL", "MASP-2", "activates", "Lectin recognition complexes activate MASP-2.", "reported"),
  rel("Ficolin", "MASP-2", "activates", "Ficolin complexes can activate lectin pathway proteases.", "reported"),
  rel("MASP-2", "C4", "cleaves", "MASP-2 cleaves C4 in lectin pathway activation.", "reported"),
  rel("MASP-2", "C2", "cleaves", "MASP-2 cleaves C2 to support C4b2a formation.", "reported"),
  rel("C4b2a", "C3", "cleaves", "Classical/lectin C3 convertase cleaves C3.", "reported"),
  rel("C3", "C3(H2O)", "activates", "Tick-over hydrolysis generates C3(H2O).", "reported"),
  rel("C3(H2O)", "Factor B", "binds_receptor", "C3(H2O) binds Factor B and supports fluid-phase initiation.", "reported"),
  rel("C3b", "Factor B", "binds_receptor", "C3b binds Factor B on activating surfaces.", "reported"),
  rel("Factor D", "Factor B", "cleaves", "Factor D cleaves C3b-bound Factor B.", "reported"),
  rel("Factor B", "Factor Bb", "cleaves", "Factor Bb is generated from Factor B cleavage.", "reported"),
  rel("C3b", "C3bBb", "forms_complex_with", "C3b forms the platform for alternative C3 convertase.", "reported"),
  rel("Factor Bb", "C3bBb", "forms_complex_with", "Bb provides the protease subunit of C3bBb.", "reported"),
  rel("Properdin", "C3bBb", "stabilizes", "Properdin stabilizes the alternative pathway convertase.", "reported"),
  rel("C3bBb", "C3", "cleaves", "Alternative pathway convertase amplifies C3 cleavage.", "reported"),
  rel("Factor H", "C3bBb", "inhibits", "Factor H accelerates decay and limits alternative activation.", "reported"),
  rel("Factor I", "C3b", "degrades", "Factor I cleaves C3b with cofactors.", "reported"),
  rel("DAF / CD55", "C3bBb", "degrades", "CD55 accelerates convertase decay.", "reported"),
  rel("MCP / CD46", "Factor I", "stabilizes", "CD46 acts as a cofactor for Factor I.", "reported"),
  rel("CR1", "Factor I", "stabilizes", "CR1 supports Factor I-mediated cleavage of C3b/C4b.", "reported"),
  rel("C3bBb", "C5", "cleaves", "C5 convertase activity cleaves C5.", "reported"),
  rel("C5", "C5a", "cleaves", "C5 cleavage releases C5a.", "reported"),
  rel("C5", "C5b", "cleaves", "C5 cleavage generates C5b.", "reported"),
  rel("C5b", "MAC", "forms_complex_with", "C5b initiates MAC assembly.", "reported"),
  rel("C6", "MAC", "forms_complex_with", "C6 participates in terminal complex assembly.", "reported"),
  rel("C7", "MAC", "forms_complex_with", "C7 participates in terminal complex assembly.", "reported"),
  rel("C8", "MAC", "forms_complex_with", "C8 participates in terminal complex assembly.", "reported"),
  rel("C9", "MAC", "forms_complex_with", "C9 polymerizes to complete MAC.", "reported"),
  rel("CD59", "MAC", "inhibits", "CD59 limits terminal MAC formation on host cells.", "reported"),
  rel("C3a", "C3aR", "binds_receptor", "C3a signals through C3aR.", "reported"),
  rel("C5a", "C5aR1", "binds_receptor", "C5a signals through C5aR1.", "reported"),
  rel("C5a", "C5aR2", "binds_receptor", "C5a also binds C5aR2 with context-dependent effects.", "reported"),
  rel("PNH", "CD59", "decreases", "PNH involves loss of GPI-anchored CD59 protection.", "reported"),
  rel("PNH", "DAF / CD55", "decreases", "PNH involves loss of GPI-anchored CD55 protection.", "reported"),
  rel("aHUS", "Factor H", "associated_with", "aHUS can involve Factor H dysregulation.", "reported"),
  rel("C3 glomerulopathy", "C3bBb", "stabilizes", "C3G is associated with alternative convertase stabilization.", "reported"),
  rel("AMD", "Factor H", "associated_with", "AMD has strong alternative pathway and Factor H biology links.", "reported"),
  rel("sepsis", "C5a", "increases", "Sepsis can involve excessive C5a inflammatory signaling.", "reported")
];

export const diseases = [
  diseaseRecord("normal", "Normal", "reference", "Balanced pathway activity and intact regulation.", ["C3 level", "C4 level", "CH50", "AH50"], ["classical", "lectin", "alternative", "terminal"], ["none"], "Reference mode for rule-based simulation."),
  diseaseRecord("PNH", "PNH", "hematology", "CD55/CD59 deficiency causing uncontrolled complement-mediated RBC lysis.", ["LDH", "hemolysis", "sC5b-9"], ["terminal"], ["C5", "C3", "Factor D", "Factor B"], "V1 models PNH as low CD55/CD59 with high MAC host-damage sensitivity."),
  diseaseRecord("aHUS", "aHUS", "renal / thrombotic microangiopathy", "Alternative pathway dysregulation with endothelial injury risk.", ["C3", "Bb", "sC5b-9"], ["alternative", "terminal"], ["C5", "Factor H", "Factor I"], "V1 models aHUS as reduced regulation and elevated endothelial damage proxy."),
  diseaseRecord("C3G", "C3 glomerulopathy", "renal", "Alternative pathway dysregulation and C3 convertase stabilization.", ["low C3", "Bb", "C3 fragments"], ["alternative"], ["C3", "Factor B", "Factor D"], "V1 models C3G as high amplification and C3 consumption pressure."),
  diseaseRecord("IgA nephropathy", "IgA nephropathy", "renal", "Lectin and alternative pathway involvement in kidney inflammation.", ["C3", "C4d", "MASP-2"], ["lectin", "alternative"], ["MASP-2", "Factor B"], "V1 increases lectin and alternative contribution."),
  diseaseRecord("AMD", "AMD", "ophthalmology", "Chronic alternative pathway activation and local inflammation.", ["C3 fragments", "Factor H", "Bb"], ["alternative"], ["C3", "Factor D", "Factor B", "C5"], "V1 models chronic alternative activation."),
  diseaseRecord("lupus nephritis", "Lupus nephritis", "autoimmune renal", "Immune complex-driven classical pathway activation.", ["C3", "C4", "CH50"], ["classical"], ["C1s", "C5"], "V1 increases classical pathway contribution."),
  diseaseRecord("cancer microenvironment", "Cancer microenvironment", "oncology", "Complement may promote inflammation, immune suppression, and angiogenesis depending context.", ["C5a", "C3a"], ["inflammatory"], ["C5aR1", "C3"], "V1 treats high C5a as the primary inflammatory driver."),
  diseaseRecord("sepsis", "Sepsis", "critical care", "High inflammatory complement activation with C5a-driven risk.", ["C5a", "C3a", "sC5b-9"], ["inflammatory", "terminal"], ["C5a", "C5aR1"], "V1 strongly weights C5a inflammatory signal.")
];

export const drugs = [
  drugRecord("C1s inhibition", "C1s", "antibody", "approved / clinical", "Reduces classical pathway initiation.", "Lower immune-complex driven C3 activation.", "May help classical-dominant diseases.", "Could reduce classical pathway host defense."),
  drugRecord("MASP-2 inhibition", "MASP-2", "antibody", "clinical", "Reduces lectin pathway activation.", "Lowers C4/C2 convertase formation from lectin triggers.", "May help lectin-associated renal inflammation.", "May impair lectin-mediated pathogen recognition."),
  drugRecord("C3 inhibition", "C3", "peptide", "approved / clinical", "Broad upstream suppression.", "Reduces C3a, C3b, C5a and MAC.", "Strong broad suppression of complement outputs.", "Higher broad immune suppression concern."),
  drugRecord("Factor B inhibition", "Factor B", "small_molecule", "clinical", "Reduces alternative amplification.", "May preserve classical/lectin initiation more than C3 inhibition.", "Useful when alternative amplification dominates.", "May reduce opsonization and bacterial defense."),
  drugRecord("Factor D inhibition", "Factor D", "small_molecule", "clinical", "Reduces Factor B cleavage in alternative pathway.", "Lowers alternative convertase generation.", "Useful in alternative-driven disorders.", "May reduce alternative pathogen defense."),
  drugRecord("C5 inhibition", "C5", "antibody", "approved", "Blocks terminal pathway output.", "Reduces C5a and MAC but not upstream C3b deposition.", "Strong reduction of terminal damage.", "Increased encapsulated bacterial infection risk."),
  drugRecord("C5aR inhibition", "C5aR1", "small_molecule", "clinical", "Blocks C5a receptor signaling.", "Reduces inflammatory response while preserving MAC generation.", "Useful when inflammatory signaling dominates.", "May affect neutrophil recruitment and host response.")
];

export const publications = [
  pub("QSP complement pathway modeling", "Systems pharmacology models demonstrate complement pathway simulation feasibility.", ["C3", "C5", "Factor B", "Factor D"], "qsp_model"),
  pub("Alternative pathway ODE modeling", "ODE models can describe C3 tick-over, convertase formation, amplification and regulation.", ["C3", "C3bBb", "Factor H"], "qsp_model"),
  pub("Terminal pathway modeling", "Terminal pathway and MAC formation can be represented with mechanistic reaction networks.", ["C5", "C5a", "MAC"], "qsp_model"),
  pub("Complement in PNH", "Terminal complement blockade validates C5/MAC biology in hemolysis.", ["PNH", "C5", "MAC"], "clinical"),
  pub("Complement in C3G", "Alternative pathway dysregulation and C3 convertase stabilization are central disease concepts.", ["C3 glomerulopathy", "C3bBb"], "review"),
  pub("Complement in AMD", "Genetic and mechanistic evidence links alternative pathway regulation to AMD biology.", ["AMD", "Factor H", "C3"], "genetic"),
  pub("C5a inflammatory signaling", "C5a/C5aR axis is a major inflammatory signaling branch.", ["C5a", "C5aR1", "sepsis"], "review"),
  pub("Lectin pathway inhibition", "MASP-2 inhibition represents a targeted approach for lectin pathway modulation.", ["MASP-2", "IgA nephropathy"], "clinical")
];

function entity(id, symbol, entity_type, description, pathway_membership, upstream_entities, downstream_entities, regulators, diseases, drug_targets, evidence_level) {
  return { id, name: id, symbol, entity_type, description, pathway_membership, upstream_entities, downstream_entities, regulators, diseases, drug_targets, evidence_level, references: [] };
}

function biomarker(id, description) {
  return entity(id, id, "biomarker", description, ["biomarker"], [], [], [], [], [], "reported");
}

function disease(id, description, pathways, biomarkers, targets) {
  return entity(id, id, "disease", description, pathways, [], biomarkers, [], [id], targets, "reported");
}

function drug(id, target, modality, description) {
  return entity(id, id, "drug", description, ["drug"], [target], [], [], [], [target], "reported");
}

function rel(source, target, relationship_type, mechanism, evidence_level) {
  return { id: `${source}->${target}:${relationship_type}`, source, target, relationship_type, direction: "directed", strength_score: null, mechanism, evidence_level, reference_ids: [] };
}

function diseaseRecord(id, disease_name, disease_category, complement_mechanism, key_biomarkers, implicated_pathways, known_targets, notes) {
  return { id, disease_name, disease_category, complement_mechanism, key_biomarkers, implicated_pathways, known_targets, notes };
}

function drugRecord(drug_name, target, modality, approved_status, upstream_effect, downstream_effect, expected_benefit, expected_risk) {
  return { id: drug_name, drug_name, target, modality, approved_status, upstream_effect, downstream_effect, expected_benefit, expected_risk, infection_risk_note: expected_risk };
}

function pub(title, key_findings, linked_entities, evidence_type) {
  return { id: title.toLowerCase().replaceAll(" ", "-"), title, authors: "Seed reference", year: "V1", journal: "Curated literature direction", doi: "", url: "", key_findings, linked_entities, evidence_type };
}
